"""Added transaction table

Revision ID: 35657c2c86a3
Revises: 8e43cba9cbb8
Create Date: 2025-05-08 15:57:45.752451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35657c2c86a3'
down_revision: Union[str, None] = '8e43cba9cbb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create monthly_expenses table first
    op.create_table('monthly_expenses',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('start_date', sa.Date(), nullable=False),
        sa.Column('end_date', sa.Date(), nullable=False),
        sa.Column('budget', sa.Float(), nullable=False),
        sa.Column('spent', sa.Float(), nullable=False),
        sa.Column('left_to_spend', sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )

    # Then create transactions table with the foreign key
    op.create_table('transactions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('amount', sa.Float(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('due_date', sa.Date(), nullable=False),
        sa.Column('sub_category', sa.String(), nullable=False),
        sa.Column('category', sa.String(), nullable=False),
        sa.Column('details', sa.String(), nullable=False),
        sa.Column('is_paid', sa.Boolean(), nullable=False),
        sa.Column('monthly_expense_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['monthly_expense_id'], ['monthly_expenses.id']),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop tables in reverse order
    op.drop_table('transactions')
    op.drop_table('monthly_expenses')
    # ### end Alembic commands ###
